# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
