# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170128_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockgroup',
            name='area_land',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='blockgroup',
            name='area_water',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='area_land',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='area_water',
            field=models.BigIntegerField(),
        ),
    ]
