# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 03:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170117_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('listing_url', models.CharField(max_length=512)),
                ('scrape_id', models.BigIntegerField()),
                ('last_scraped', models.DateField()),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('host_id', models.BigIntegerField()),
                ('host_name', models.CharField(max_length=512)),
                ('host_since', models.DateField()),
                ('host_is_superhost', models.BooleanField()),
                ('host_identity_verified', models.BooleanField()),
                ('neighbourhood_cleansd', models.CharField(max_length=512)),
                ('property_type', models.CharField(max_length=512)),
                ('room_type', models.CharField(max_length=512)),
                ('accommodates', models.IntegerField()),
                ('bathrooms', models.FloatField()),
                ('bedrooms', models.FloatField()),
                ('bed_type', models.CharField(max_length=512)),
                ('amenities', models.TextField()),
                ('price', models.FloatField()),
                ('minimum_nights', models.IntegerField()),
                ('availability_365', models.IntegerField()),
                ('number_of_reviews', models.IntegerField()),
                ('reviews_per_month', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
