# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170122_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='summary',
        ),
    ]
