# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170128_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockgroup',
            name='geoid',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zipcode',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
