# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170128_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockgroup',
            name='land_area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockgroup',
            name='water_area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zipcode',
            name='land_area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zipcode',
            name='water_area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
