# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_listing_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='neighbourhood_cleansd',
        ),
        migrations.AddField(
            model_name='listing',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Neighborhood'),
        ),
        migrations.AddField(
            model_name='listing',
            name='street',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
    ]
