# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170129_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockgroup',
            name='area_land',
        ),
        migrations.RemoveField(
            model_name='blockgroup',
            name='area_water',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='area_land',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='area_water',
        ),
    ]
