# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 02:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_listing_neighbourhood_cleansed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField()),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'ordering': ['zipcode'],
            },
        ),
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['name']},
        ),
    ]
