# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 02:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170125_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='poly',
        ),
        migrations.AddField(
            model_name='zipcode',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
