# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170129_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockgroup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='blockgroup',
            name='geoid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='geoid',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
