# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170125_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
