# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170129_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='block_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.BlockGroup'),
        ),
        migrations.AddField(
            model_name='listing',
            name='zipcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Zipcode'),
        ),
    ]
