# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 09:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170125_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips_code', models.CharField(max_length=12)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
