# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_blockgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockgroup',
            old_name='fips_code',
            new_name='geoid',
        ),
    ]
