# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 09:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170131_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.BigIntegerField()),
                ('date_reported', models.DateField()),
                ('date_occurred', models.DateTimeField()),
                ('crime_code', models.IntegerField()),
                ('crime_code_desc', models.TextField(max_length=512)),
                ('address', models.TextField(max_length=512)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
