# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_crime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='address',
        ),
    ]
