# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170125_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zipcode',
            options={},
        ),
    ]
