# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_crime_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='block_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.BlockGroup'),
        ),
        migrations.AddField(
            model_name='crime',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Neighborhood'),
        ),
        migrations.AddField(
            model_name='crime',
            name='zipcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Zipcode'),
        ),
    ]
