# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_county'),
    ]

    operations = [
        migrations.DeleteModel(
            name='County',
        ),
    ]
