# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_county'),
    ]

    operations = [
    ]
