# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_add_indices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='block_group',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='block_group',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
    ]
