# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 05:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170204_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={},
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='computed_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
