# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170205_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockgroup',
            old_name='data',
            new_name='fixed_data',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='data',
            new_name='fixed_data',
        ),
        migrations.RenameField(
            model_name='zipcode',
            old_name='data',
            new_name='fixed_data',
        ),
    ]
