# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20170208_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='amenities',
            new_name='raw_amenities',
        ),
    ]
