# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 00:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_neighborhood_centroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockgroup',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='blockgroup',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Neighborhood'),
        ),
    ]
