# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 00:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20170221_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.CharField(max_length=12)),
                ('land_area', models.FloatField()),
                ('water_area', models.FloatField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('fixed_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Neighborhood')),
            ],
        ),
    ]
