# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_tract'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Tract'),
        ),
    ]
