# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_listing_tract'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='random',
            field=models.IntegerField(db_index=True, default=main.models.rand_num),
        ),
    ]
